# Credit Risk Resampling Techniques

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [96]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [97]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.shape

(68817, 86)

# Split the Data into Training and Testing

In [99]:
#Create the training variables 

# Create our features
X = df.drop(columns='loan_status')
string_columns = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X,columns=string_columns)

# Create our target
y = df[target]
#y = pd.get_dummies(y,columns=['loan_status'])

print(y.shape)
print(X.shape)

(68817, 1)
(68817, 95)


In [100]:
X

loan_amnt  int_rate  installment  annual_inc    dti  delinq_2yrs  \
0        10500.0    0.1719       375.35     66000.0  27.24          0.0   
1        25000.0    0.2000       929.09    105000.0  20.23          0.0   
2        20000.0    0.2000       529.88     56000.0  24.26          0.0   
3        10000.0    0.1640       353.55     92000.0  31.44          0.0   
4        22000.0    0.1474       520.39     52000.0  18.76          0.0   
...          ...       ...          ...         ...    ...          ...   
68812    10000.0    0.1502       346.76     26000.0   9.60          0.0   
68813    12000.0    0.2727       368.37     63000.0  29.07          0.0   
68814     5000.0    0.1992       185.62     52000.0  14.86          0.0   
68815    40000.0    0.0646      1225.24    520000.0   9.96          0.0   
68816    16000.0    0.1131       350.36     72000.0   7.02          2.0   

       inq_last_6mths  open_acc  pub_rec  revol_bal  ...  issue_d_Mar-2019  \
0                 0.0       8.0      0.0     1609.0  ...                 1   
1                 0.0      17.0      1.0    18368.0  ...                 1   
2                 0.0       8.0      0.0    13247.0  ...                 1   
3                 1.0      10.0      1.0    17996.0  ...                 1   
4                 1.0      14.0      0.0     9091.0  ...                 1   
...               ...       ...      ...        ...  ...               ...   
68812             0.0       9.0      0.0     2684.0  ...                 0   
68813             0.0       8.0      0.0    13314.0  ...                 0   
68814             0.0       5.0      1.0     3715.0  ...                 0   
68815             1.0      21.0      0.0    59529.0  ...                 0   
68816             0.0      12.0      1.0    11882.0  ...                 0   

       pymnt_plan_n  initial_list_status_f  initial_list_status_w  \
0                 1                      0                      1   
1                 1                      0                      1   
2                 1                      0                      1   
3                 1                      0                      1   
4                 1                      0                      1   
...             ...                    ...                    ...   
68812             1                      0                      1   
68813             1                      0                      1   
68814             1                      0                      1   
68815             1                      1                      0   
68816             1                      0                      1   

       next_pymnt_d_Apr-2019  next_pymnt_d_May-2019  \
0                          0                      1   
1                          0                      1   
2                          0                      1   
3                          0                      1   
4                          0                      1   
...                      ...                    ...   
68812                      0                      1   
68813                      0                      1   
68814                      0                      1   
68815                      0                      1   
68816                      0                      1   

       application_type_Individual  application_type_Joint App  \
0                                1                           0   
1                                1                           0   
2                                1                           0   
3                                1                           0   
4                                1                           0   
...                            ...                         ...   
68812                            1                           0   
68813                            1                           0   
68814                            1                           0   
68815              

In [49]:
X.describe()

loan_amnt      int_rate   installment    annual_inc           dti  \
count      8.000000      8.000000      8.000000  8.000000e+00      8.000000   
mean   23096.492894   8602.238256   9076.403162  1.162144e+06   8739.785925   
std    21827.118360  24330.437918  24143.942622  3.085355e+06  24277.293337   
min     1000.000000      0.048130     30.890000  4.000000e+01      0.000000   
25%     9958.011442      0.081075    282.479324  6.411275e+04     18.292500   
50%    15838.797281      0.122859    442.606431  8.060685e+04     20.988698   
75%    28000.000000      0.193875    905.132500  1.068950e+05    269.745000   
max    68817.000000  68817.000000  68817.000000  8.797500e+06  68817.000000   

        delinq_2yrs  inq_last_6mths      open_acc       pub_rec  \
count      8.000000        8.000000      8.000000      8.000000   
mean    8604.492017     8603.031977   8618.076276   8602.682853   
std    24329.528064    24330.117263  24324.048662  24330.258313   
min        0.000000        0.000000      2.000000      0.000000   
25%        0.000000        0.000000      7.505717      0.000000   
50%        0.108883        0.627909     11.793670      0.063015   
75%        5.038775        2.000000     30.000000      1.252598   
max    68817.000000    68817.000000  68817.000000  68817.000000   

           revol_bal  ...  issue_d_Mar-2019  pymnt_plan_n  \
count       8.000000  ...          8.000000      8.000000   
mean    91943.002904  ...       8602.319889   8602.875000   
std    201191.196883  ...      24330.404936  24330.180637   
min         0.000000  ...          0.000000      0.000000   
25%     10624.250000  ...          0.000000      1.000000   
50%     19669.571414  ...          0.088619      1.000000   
75%     33581.160300  ...          0.536405      1.000000   
max    587191.000000  ...      68817.000000  68817.000000   

       initial_list_status_f  initial_list_status_w  next_pymnt_d_Apr-2019  \
count               8.000000               8.000000               8.000000   
mean             8602.306666            8602.775696            8602.483665   
std             24330.410279           24330.220763           24330.338761   
min                 0.000000               0.000000               0.000000   
25%                 0.000000               0.739452               0.000000   
50%                 0.061940               1.000000               0.434661   
75%                 0.497085               1.000000               1.000000   
max             68817.000000           68817.000000           68817.000000   

       next_pymnt_d_May-2019  application_type_Individual  \
count               8.000000                     8.000000   
mean             8602.637875                  8602.775872   
std             24330.276451                 24330.220691   
min                 0.000000                     0.000000   
25%                 0.364620                     0.731914   
50%                 0.808419                     1.000000   
75%                 1.000000                     1.000000   
max             68817.000000                 68817.000000   

       application_type_Joint App  hardship_flag_N  debt_settlement_flag_N  
count                    8.000000         8.000000                8.000000  
mean                  8602.310787      8602.875000             8602.875000  
std                  24330.408614     24330.180637            24330.180637  
min                      0.000000         0.000000                0.000000  
25%                      0.000000         1.000000                1.000000  
50%                      0.069830         1.000000                1.000000  
75%                      0.509978         1.000000                1.000000  
max                  68817.000000     68817.000000            68817.000000  

[8 rows x 95 columns]

In [101]:
# Check the balance of our target values
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

Counter(y_train['loan_status'])



Counter({'low_risk': 51343, 'high_risk': 269})

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [115]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
print(X.shape)
print(X_train.shape)
print(X_test.shape)
print(X_resampled.shape)
#y_resampled.replace({'low_risk':0,'high_risk':1}, inplace = True)
Counter(y_resampled['loan_status'])


(68817, 95)
(51612, 95)
(17205, 95)
(102686, 95)


Counter({'low_risk': 51343, 'high_risk': 51343})

In [116]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [119]:
# Calculated the balanced accuracy score

from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6480197708521408

In [120]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)


array([[   49,    29],
       [ 5689, 11438]])

In [121]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.63      0.67      0.02      0.65      0.42        78
   low_risk       1.00      0.67      0.63      0.80      0.65      0.42     17127

avg / total       0.99      0.67      0.63      0.80      0.65      0.42     17205



### SMOTE Oversampling

In [123]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,
sampling_strategy='auto').fit_resample(
   X_train, y_train)
Counter(y_resampled['loan_status'])


Counter({'low_risk': 51343, 'high_risk': 51343})

In [124]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [125]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6653944963193519

In [126]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)


array([[   51,    27],
       [ 5533, 11594]])

In [127]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))


                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.65      0.68      0.02      0.67      0.44        78
   low_risk       1.00      0.68      0.65      0.81      0.67      0.44     17127

avg / total       0.99      0.68      0.65      0.80      0.67      0.44     17205



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [128]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete


from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

Counter(y_resampled['loan_status'])



Counter({'high_risk': 269, 'low_risk': 269})

In [129]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [130]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.5338680266425931

In [131]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)


array([[  47,   31],
       [9160, 7967]])

In [132]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))


                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.60      0.47      0.01      0.53      0.28        78
   low_risk       1.00      0.47      0.60      0.63      0.53      0.28     17127

avg / total       0.99      0.47      0.60      0.63      0.53      0.28     17205



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [133]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

In [134]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [135]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6659379477298553

In [136]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)


array([[  59,   19],
       [7271, 9856]])

In [137]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))


                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.76      0.58      0.02      0.66      0.44        78
   low_risk       1.00      0.58      0.76      0.73      0.66      0.43     17127

avg / total       0.99      0.58      0.76      0.73      0.66      0.43     17205

